name:Learning GitHub script
push:On
issues:On
types:[opened]
jobs:On
comment:On
runs-on:ubuntu-latest
steps:On
-uses:actions/github.scripts@0.8.0
with:github-token:${{secreats.GITHUB-TOKEN}}
script:github.issues.createcomment({
issue_number:context.issue.number,
owner:context.repo.owner,
repo:context.repo.repo,
body:"you have created this issue comment using Github script !!!"
